# -*- coding: utf-8 -*-
"""Network_Intrusion_Detection_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15CZ-rYv9WmZyKWUKmURzu6PYNss7QQEd
"""

# Import necessary libraries

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import matplotlib.pyplot as plt
import seaborn as sns

# Upload the dataset

from google.colab import files

uploaded = files.upload()

# Define column names

columns = [
    'duration','protocol_type','service','flag','src_bytes',
    'dst_bytes','land','wrong_fragment','urgent','hot',
    'num_failed_logins','logged_in','num_compromised',
    'root_shell','su_attempted','num_root','num_file_creations',
    'num_shells','num_access_files','num_outbound_cmds',
    'is_host_login','is_guest_login','count','srv_count',
    'serror_rate','srv_serror_rate','rerror_rate',
    'srv_rerror_rate','same_srv_rate','diff_srv_rate',
    'srv_diff_host_rate','dst_host_count','dst_host_srv_count',
    'dst_host_same_srv_rate','dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate','dst_host_srv_diff_host_rate',
    'dst_host_serror_rate','dst_host_srv_serror_rate',
    'dst_host_rerror_rate','dst_host_srv_rerror_rate',
    'attack','difficulty'
]

# Load the training and testing datasets

train_df = pd.read_csv("KDDTrain+.txt", names=columns)
test_df = pd.read_csv("KDDTest+.txt", names=columns)

# Preview / Display the training dataset

train_df.head()

# Display training dataset information

train_df.info()

# Preview / Display the test dataset

test_df.head()

# Display test dataset information

test_df.info()

# Check number of rows and columns in each dataset

print("Training Data:", train_df.shape)

print("Testing Data:", test_df.shape)

# Display statistical summary of training dataset

train_df.describe()

# Display statistical summary of test dataset

test_df.describe()

# Check missing values in the training and testing datasets

train_df.isnull().sum()
train_df.fillna(train_df.mean(numeric_only=True), inplace=True)

test_df.isnull().sum()
test_df.fillna(test_df.mean(numeric_only=True), inplace=True)

# Check duplicate rows in the training and testing datasets

train_df.duplicated().sum()
train_df.drop_duplicates(inplace=True)

test_df.duplicated().sum()
test_df.drop_duplicates(inplace=True)

# Check target column in the training and testing datasets

print(train_df['attack'].value_counts())
print()
print(test_df['attack'].value_counts())

# Convert attack labels into binary values

train_df['attack'] = train_df['attack'].apply(
    lambda x: 0 if x == 'normal' else 1
)

test_df['attack'] = test_df['attack'].apply(
    lambda x: 0 if x == 'normal' else 1
)

# Separate input features and target variable

X_train = train_df.drop(['attack','difficulty'], axis=1)

y_train = train_df['attack']


X_test = test_df.drop(['attack','difficulty'], axis=1)

y_test = test_df['attack']

# Save feature names

feature_names = X_train.columns

categorical_columns = X_train.select_dtypes(include='object').columns

label_encoders = {}

for column in categorical_columns:
    encoder = LabelEncoder()

    X_train[column] = encoder.fit_transform(X_train[column])

    X_test[column] = encoder.transform(X_test[column])

    label_encoders[column] = encoder

# Scale feature values

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

# Train Logistic Regression model

lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_model.fit(X_train,y_train)

y_pred_lr = lr_model.predict(X_test)

lr_accuracy = accuracy_score(y_test,y_pred_lr)

print(f"Accuracy of the Logistic Regression: {lr_accuracy * 100:.2f}%")

# Train Decision Tree Classifier

dt_model = DecisionTreeClassifier(
    max_depth=10,
    random_state=42
)

dt_model.fit(X_train,y_train)

y_pred_dt = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test,y_pred_dt)

print(f"Accuracy of the Decision Tree: {dt_accuracy * 100:.2f}%")

# Train Random Forest Classifier

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42
)

rf_model.fit(X_train,y_train)

y_pred_rf = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test,y_pred_rf)

print(f"Accuracy of the Random Forest: {rf_accuracy * 100:.2f}%")

# Compare model accuracy

model_comparison = pd.DataFrame({

    "Model":[
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],

    "Accuracy(%)":[
        lr_accuracy*100,
        dt_accuracy*100,
        rf_accuracy*100
    ]

})


model_comparison

# Plot model accuracy comparison

plt.figure(figsize=(7,4))

sns.barplot(
    x="Model",
    y="Accuracy(%)",
    data=model_comparison
)

plt.title("Model Accuracy Comparison")

plt.ylabel("Accuracy(%)")

plt.show()

# Find the best model

best_model = model_comparison.loc[
    model_comparison["Accuracy(%)"].idxmax()
]

print(best_model)

# Selecting Random Forest as the final model

final_model = rf_model

# Creating Confusion Matrix

cm = confusion_matrix(y_test, y_pred_rf)

print(cm)

# Plotting Confusion Matrix

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

# Display classification report

print(classification_report(y_test, y_pred_rf))

# Calculate feature importance

feature_importance = pd.DataFrame({

    "Feature": train_df.drop(['attack', 'difficulty'], axis=1).columns,
    "Importance": rf_model.feature_importances_

})

# Sort feature importance

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

feature_importance.head(15)

# Plot feature importance

plt.figure(figsize=(8,5))

sns.barplot(
    x="Importance",
    y="Feature",
    data=feature_importance.head(15)
)

plt.title("Top 15 Feature Importance")

plt.show()

# Function for intrusion prediction

def predict_intrusion(input_data):

    input_df = pd.DataFrame(
        [input_data],
        columns=feature_names
    )

    for col in categorical_columns:
        input_df[col] = label_encoders[col].transform(
            input_df[col]
        )

    input_scaled = scaler.transform(input_df)

    prediction = final_model.predict(input_scaled)

    return prediction[0]

# Create new data

new_data = {
    'duration': 0,
    'protocol_type': 'tcp',
    'service': 'http',
    'flag': 'SF',
    'src_bytes': 181,
    'dst_bytes': 5450,
    'land': 0,
    'wrong_fragment': 0,
    'urgent': 0,
    'hot': 0,
    'num_failed_logins': 0,
    'logged_in': 1,
    'num_compromised': 0,
    'root_shell': 0,
    'su_attempted': 0,
    'num_root': 0,
    'num_file_creations': 0,
    'num_shells': 0,
    'num_access_files': 0,
    'num_outbound_cmds': 0,
    'is_host_login': 0,
    'is_guest_login': 0,
    'count': 9,
    'srv_count': 9,
    'serror_rate': 0.0,
    'srv_serror_rate': 0.0,
    'rerror_rate': 0.0,
    'srv_rerror_rate': 0.0,
    'same_srv_rate': 1.0,
    'diff_srv_rate': 0.0,
    'srv_diff_host_rate': 0.0,
    'dst_host_count': 255,
    'dst_host_srv_count': 9,
    'dst_host_same_srv_rate': 0.04,
    'dst_host_diff_srv_rate': 0.06,
    'dst_host_same_src_port_rate': 0.00,
    'dst_host_srv_diff_host_rate': 0.00,
    'dst_host_serror_rate': 0.00,
    'dst_host_srv_serror_rate': 0.00,
    'dst_host_rerror_rate': 0.00,
    'dst_host_srv_rerror_rate': 0.00
}

# Predict network intrusion

result = predict_intrusion(new_data)

print("Prediction:", result)

# Display prediction result

if (result == 1):
    print("⚠️ Intrusion Detected")

else:
    print("✅ Normal Network Traffic")

# Create another new data

new_data1 = {
    'duration': 120,
    'protocol_type': 'tcp',
    'service': 'ftp_data',
    'flag': 'S0',
    'src_bytes': 5000,
    'dst_bytes': 0,
    'land': 0,
    'wrong_fragment': 0,
    'urgent': 0,
    'hot': 5,
    'num_failed_logins': 4,
    'logged_in': 0,
    'num_compromised': 3,
    'root_shell': 1,
    'su_attempted': 1,
    'num_root': 2,
    'num_file_creations': 3,
    'num_shells': 1,
    'num_access_files': 2,
    'num_outbound_cmds': 0,
    'is_host_login': 0,
    'is_guest_login': 1,
    'count': 250,
    'srv_count': 250,
    'serror_rate': 1.0,
    'srv_serror_rate': 1.0,
    'rerror_rate': 0.8,
    'srv_rerror_rate': 0.8,
    'same_srv_rate': 0.1,
    'diff_srv_rate': 0.9,
    'srv_diff_host_rate': 0.8,
    'dst_host_count': 255,
    'dst_host_srv_count': 5,
    'dst_host_same_srv_rate': 0.02,
    'dst_host_diff_srv_rate': 0.90,
    'dst_host_same_src_port_rate': 0.90,
    'dst_host_srv_diff_host_rate': 0.80,
    'dst_host_serror_rate': 1.0,
    'dst_host_srv_serror_rate': 1.0,
    'dst_host_rerror_rate': 0.9,
    'dst_host_srv_rerror_rate': 0.9
}

# Predict network intrusion

result1 = predict_intrusion(new_data1)

print("Prediction:", result1)

# Display prediction result

if (result1 == 1):
    print("⚠️ Intrusion Detected")

else:
    print("✅ Normal Network Traffic")